#!/bin/bash
# Create self-extracting UCM installer

set -e

VERSION="${1:-1.8.3}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_FILE="$PROJECT_ROOT/ucm-installer-${VERSION}.sh"

echo "Creating self-extracting installer for UCM v${VERSION}..."

cd "$PROJECT_ROOT"

# Create temporary tarball
TEMP_TAR=$(mktemp)
tar czf "$TEMP_TAR" \
  --exclude='.git' \
  --exclude='debian' \
  --exclude='__pycache__' \
  --exclude='*.pyc' \
  --exclude='backend/data/*.db' \
  backend/ frontend/ packaging/ .env.example README.md CHANGELOG.md

# Create installer script
cat > "$OUTPUT_FILE" << 'INSTALLER_HEADER'
#!/bin/bash
# UCM Self-Extracting Installer
# Generated by create-installer.sh

set -e

VERSION="VERSION_PLACEHOLDER"
INSTALL_DIR="/opt/ucm"
DATA_DIR="$INSTALL_DIR/backend/data"
SERVICE_FILE="/etc/systemd/system/ucm.service"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    log_error "Please run as root (use sudo)"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    OS_VERSION=$VERSION_ID
else
    log_error "Cannot detect OS"
    exit 1
fi

log_info "Detected OS: $OS $OS_VERSION"
log_info "Installing Ultimate CA Manager v${VERSION}..."

# Install dependencies based on OS
install_dependencies() {
    log_info "Installing dependencies..."
    
    case "$OS" in
        ubuntu|debian)
            apt-get update
            apt-get install -y python3 python3-pip python3-venv systemd openssl adduser
            ;;
        rhel|rocky|almalinux|centos|fedora)
            if command -v dnf &> /dev/null; then
                dnf install -y python3 python3-pip systemd openssl
            else
                yum install -y python3 python3-pip systemd openssl
            fi
            ;;
        *)
            log_error "Unsupported OS: $OS"
            exit 1
            ;;
    esac
    
    log_success "Dependencies installed"
}

# Extract embedded archive
extract_archive() {
    log_info "Extracting UCM files..."
    
    ARCHIVE_LINE=$(awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit}' "$0")
    
    mkdir -p "$INSTALL_DIR"
    tail -n +${ARCHIVE_LINE} "$0" | tar xzf - -C "$INSTALL_DIR"
    
    log_success "Files extracted to $INSTALL_DIR"
}

# Create ucm user
create_user() {
    if ! id -u ucm &>/dev/null; then
        log_info "Creating ucm user..."
        useradd -r -s /bin/bash -d "$INSTALL_DIR" -c "UCM Service Account" ucm || true
        log_success "User created"
    fi
}

# Setup Python environment
setup_python() {
    log_info "Setting up Python virtual environment..."
    
    cd "$INSTALL_DIR/backend"
    
    python3 -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    
    log_success "Python environment ready"
}

# Initialize database
init_database() {
    log_info "Initializing database..."
    
    mkdir -p "$DATA_DIR"/{ca,certs,private,crl,backups,scep}
    
    cd "$INSTALL_DIR/backend"
    source venv/bin/activate
    
    if [ ! -f "$DATA_DIR/ucm.db" ]; then
        python3 init_db.py
        log_success "Database initialized"
    else
        log_warn "Database already exists, skipping initialization"
    fi
}

# Install systemd service
install_service() {
    log_info "Installing systemd service..."
    
    cat > "$SERVICE_FILE" << 'SERVICEEOF'
[Unit]
Description=Ultimate CA Manager
After=network.target

[Service]
Type=simple
User=ucm
Group=ucm
WorkingDirectory=/opt/ucm/backend
Environment="PATH=/opt/ucm/backend/venv/bin:/usr/local/bin:/usr/bin:/bin"
ExecStart=/opt/ucm/backend/venv/bin/gunicorn --config /opt/ucm/backend/gunicorn_config.py wsgi:application
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
SERVICEEOF

    systemctl daemon-reload
    log_success "Service installed"
}

# Set permissions
set_permissions() {
    log_info "Setting permissions..."
    
    chown -R ucm:ucm "$INSTALL_DIR"
    chmod -R 750 "$INSTALL_DIR"
    chmod 700 "$DATA_DIR"
    
    log_success "Permissions set"
}

# Main installation
main() {
    echo ""
    echo "╔════════════════════════════════════════════════════════╗"
    echo "║   Ultimate CA Manager - Self-Extracting Installer     ║"
    echo "║                    Version ${VERSION}                       ║"
    echo "╚════════════════════════════════════════════════════════╝"
    echo ""
    
    install_dependencies
    extract_archive
    create_user
    setup_python
    init_database
    install_service
    set_permissions
    
    echo ""
    log_success "════════════════════════════════════════════════════"
    log_success "   Installation Complete!"
    log_success "════════════════════════════════════════════════════"
    echo ""
    log_info "To start UCM:"
    echo "  sudo systemctl enable --now ucm"
    echo ""
    log_info "Access UCM at:"
    echo "  https://$(hostname -f):8443"
    echo "  https://localhost:8443"
    echo ""
    log_warn "Default credentials:"
    echo "  Username: admin"
    echo "  Password: changeme123"
    echo ""
    log_error "⚠️  CHANGE THE PASSWORD IMMEDIATELY!"
    echo ""
    
    exit 0
}

main

__ARCHIVE_BELOW__
INSTALLER_HEADER

# Replace version placeholder
sed -i "s/VERSION_PLACEHOLDER/$VERSION/g" "$OUTPUT_FILE"

# Append the tarball
cat "$TEMP_TAR" >> "$OUTPUT_FILE"

# Cleanup
rm "$TEMP_TAR"

# Make executable
chmod +x "$OUTPUT_FILE"

FILE_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
echo "[OK] Self-extracting installer created: $OUTPUT_FILE ($FILE_SIZE)"

echo ""
echo "Usage:"
echo "  sudo bash ucm-installer-${VERSION}.sh"
echo ""

